Switch to Bootstrap 4.
SwiftWeekly/swiftweekly.github.io pull request #618
Opened 2021-03-13 20:24 UTC by jeroenleenarts

Still one issue.

The social links at the top are not yet behaving in regards to button color. Not sure yet why. Maybe someone knows?

2021-03-13 20:25 UTC, jeroenleenarts commented
Partial of #469

2021-03-13 20:26 UTC, fassko commented
Sorry pressed wrong buton. :D

2021-03-13 20:27 UTC, fassko submitted a review, later dismissed
I'm not a web developer but looks good to me.

2021-03-14 11:19 UTC, fassko requested changes
Do we need that comment?

2021-03-14 11:19 UTC, fassko commented on css/style.css
> +/*   color: var(--link-fg-visited);*/
Is this needed? :)

2021-03-19 08:37 UTC, fassko approved these changes
Looks good, thanks!

2021-03-19 09:37 UTC, merged